# Generated by Django 2.1.7 on 2019-03-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Intersex')])),
                ('occupation', models.CharField(max_length=64)),
                ('disease', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1024)),
                ('update_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
        migrations.CreateModel(
            name='TestTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('note', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Anonymous')])),
                ('level', models.CharField(choices=[('L1', 'Advanced User'), ('L2', 'Standard User'), ('L3', 'Beginner User')], max_length=2)),
                ('email', models.EmailField(max_length=128)),
                ('address', models.CharField(max_length=128, null=True)),
                ('portrait', models.ImageField(null=True, upload_to='')),
                ('update_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
