# Generated by Django 2.1.7 on 2019-04-01 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_User_Control', '0002_searchhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patients',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
