# Generated by Django 2.1.7 on 2019-04-01 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_User_Control', '0003_auto_20190401_1751'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestTable',
            new_name='Patient',
        ),
    ]
