# Generated by Django 2.1.7 on 2019-04-02 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_User_Control', '0006_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='device',
            field=models.CharField(help_text='Max length is 1024, multiple devices split by comma.', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='userpatient',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App_User_Control.Patient'),
        ),
        migrations.AddField(
            model_name='userpatient',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
